-- EXISTS = 중복성을 없애고 싶을 때 사용하는 쿼리

-- ex
SELECT 10 FROM dual
WHERE EXISTS(SELECT 1 FROM DUAL WHERE 1 < 2)

-- 숙제 : EXIST 문을 사용해서 KEYWORD_LIST를 LEFT OUTER JOIN했을때 행이 중복해서 나오는 것을 해결하시오.
WITH KEYWORD_LIST AS (
SELECT TRIM(REGEXP_SUBSTR('매트,릭스,어바,터스','[^,]+', 1, LEVEL)) AS KEYWORD
FROM DUAL
CONNECT BY TRIM(REGEXP_SUBSTR('매트,릭스,어바,터스','[^,]+', 1, LEVEL)) IS NOT NULL
)
SELECT A.* FROM VSM_MOVIE_INFO A
WHERE EXISTS(SELECT * FROM KEYWORD_LIST B WHERE A.MOVIE_NM LIKE '%' || B.KEYWORD || '%')
