-- 1. 대여기록 테이블만 가지고 해당 테이프가 연체인지 판단하는 로직만 완성해보기.
-- 연체 : RETURN_DATE > RENT_DATE
--
SELECT * FROM VSM_RENT_RECORD
SELECT * FROM VSM_TAPE_INFO


WITH T_RENT_GRP AS
    ( SELECT TAPE_CD, RENT_DATE, RETURN_DUE_DATE, RETURN_DATE
      FROM VSM_RENT_RECORD  WHERE RETURN_DUE_DATE < RETURN_DATE
                               OR RENT_DATE IS NOT NULL AND RETURN_DATE IS NULL
    )

SELECT
    A.TAPE_CD
,   B.TAPE_CD LATE_TAPE
,   CASE
        WHEN A.TAPE_CD = B.TAPE_CD THEN '연체중'
        ELSE '연체없음'
        END LATE_RETURN
FROM VSM_TAPE_INFO A

LEFT OUTER JOIN T_RENT_GRP B
ON B.TAPE_CD = A.TAPE_CD

