
WITH T_RENT_GRP AS 
    ( SELECT * FROM (SELECT TAPE_CD, RENT_DATE, RETURN_DATE, ROW_NUMBER() OVER
    ( PARTITION BY TAPE_CD
      ORDER BY RENT_DATE DESC 
    )RENT_AB
      FROM VSM_RENT_RECORD)
      WHERE RENT_AB = 1  
    ) 
  
SELECT 
    A.TAPE_CD
,    B.RENT_DATE
,   B.RETURN_DATE
,   CASE 
         WHEN B.RENT_DATE IS NOT NULL AND B.RETURN_DATE IS NULL
         THEN '대여불가'
         ELSE '대여가능'
         END RENT_ABILITY
    
FROM VSM_TAPE_INFO A

LEFT OUTER JOIN T_RENT_GRP B
ON B.TAPE_CD = A.TAPE_CD