
-- 영화장르
SELECT CO_CD CATE_CD
,      CO_CD_NM CATE_NM
FROM VSM_CO_CD WHERE GRP_CD = '01'
ORDER BY CO_CD

-- 영화구분
SELECT CO_CD MV_TYPE_CD
,      CO_CD_NM MV_TYPE_NM
FROM VSM_CO_CD WHERE GRP_CD = '00'
ORDER BY CO_CD

-- 테이프 방식
SELECT CO_CD TAPE_TYPE_CD
,      CO_CD_NM TAPE_TYPE_NM
FROM VSM_CO_CD WHERE GRP_CD = '02'
ORDER BY CO_CD

